# Makefile for LagoonAtHome — Lagoon on k3s for homelabs
SHELL := /bin/bash
.ONESHELL:
.SHELLFLAGS := -eu -o pipefail -c
.DEFAULT_GOAL := all

# Load user configuration (generated by install.sh or copied from .env.example)
-include .env
export

export KUBECONFIG := $(HOME)/.kube/config
KUBECTL := kubectl

# Variables that must be set (either via .env or environment)
DOMAIN ?= $(NODE_IP).nip.io
CLUSTER_ISSUER ?= lagoon-issuer
TLS_MODE ?= selfsigned
ORG_NAME ?= lagoon
ADMIN_EMAIL ?= admin@example.com
ADMIN_PASSWORD ?= changeme
ADMIN_FIRST_NAME ?= Admin
ADMIN_LAST_NAME ?= User
SSH_KEY_PATH ?= $(HOME)/.ssh/id_ed25519
MINIO_PASSWORD ?= changeme
HARBOR_PASSWORD ?= changeme
POSTGRES_PASSWORD ?= changeme
MARIADB_PASSWORD ?= changeme
LAGOON_NETWORK_RANGE ?= 192.168.1.150-192.168.1.160
NODE_IP ?= 192.168.1.150
INSTALL_HARBOR ?= false
INSTALL_PROMETHEUS ?= false
INSTALL_POSTGRES ?= true
INSTALL_MARIADB ?= true
INSTALL_HEADLAMP ?= false

# Explicit list of variables for envsubst (avoids clobbering $$i, $$namespace, etc. in YAML)
ENVSUBST_VARS := '$${DOMAIN} $${CLUSTER_ISSUER} $${ADMIN_EMAIL} $${ADMIN_PASSWORD} \
	$${ORG_NAME} $${MINIO_PASSWORD} $${HARBOR_PASSWORD} $${POSTGRES_PASSWORD} \
	$${MARIADB_PASSWORD} $${ACME_EMAIL} $${CLOUDFLARE_API_TOKEN} $${NODE_IP} \
	$${LAGOON_NETWORK_RANGE} $${BASE_URL}'

# Backwards compat
BASE_URL := $(DOMAIN)

# OS detection
OS := $(shell uname -s | tr '[:upper:]' '[:lower:]')
ARCH := $(shell uname -m)
ifeq ($(ARCH),x86_64)
  ARCH := amd64
endif
ifeq ($(ARCH),aarch64)
  ARCH := arm64
endif

.PHONY: basic all core-dependencies extras generate-config \
	k3s system helm-repos helm metallb cert-manager gatekeeper ingress \
	harbor registry minio postgres mariadb prometheus headlamp \
	lagoon-core lagoon-remote lagoon-config post-install \
	build-deploy-tool push-local-build-image \
	clean-bdt clean-ssh nuke

# --- High-level targets ---
basic: generate-config core-dependencies lagoon-core lagoon-remote lagoon-config build-deploy-tool push-local-build-image

all: generate-config core-dependencies extras lagoon-core lagoon-remote lagoon-config

core-dependencies: k3s system helm-repos metallb cert-manager gatekeeper ingress registry minio

extras:
	@$(MAKE) _optional_harbor
	@$(MAKE) _optional_prometheus
	@$(MAKE) _optional_postgres
	@$(MAKE) _optional_mariadb
	@$(MAKE) _optional_headlamp

_optional_harbor:
	@if [ "$(INSTALL_HARBOR)" = "true" ]; then $(MAKE) harbor; fi

_optional_prometheus:
	@if [ "$(INSTALL_PROMETHEUS)" = "true" ]; then $(MAKE) prometheus; fi

_optional_postgres:
	@if [ "$(INSTALL_POSTGRES)" = "true" ]; then $(MAKE) postgres; fi

_optional_mariadb:
	@if [ "$(INSTALL_MARIADB)" = "true" ]; then $(MAKE) mariadb; fi

_optional_headlamp:
	@if [ "$(INSTALL_HEADLAMP)" = "true" ]; then $(MAKE) headlamp; fi

# --- Config generation ---
generate-config:
	@echo "Generating config from templates"
	mkdir -p build/config build/values generated/ssh-host-keys
	# Template config files
	for tpl in config/*.tpl; do \
		out="build/config/$$(basename "$${tpl%.tpl}")"; \
		envsubst $(ENVSUBST_VARS) < "$$tpl" > "$$out"; \
	done
	# Template values files
	for tpl in values/*.tpl; do \
		out="build/values/$$(basename "$${tpl%.tpl}")"; \
		envsubst $(ENVSUBST_VARS) < "$$tpl" > "$$out"; \
	done
	# Copy static config files
	for f in config/*.yml; do \
		cp "$$f" "build/config/$$(basename "$$f")"; \
	done
	# Copy static values files
	for f in values/*.yml; do \
		cp "$$f" "build/values/$$(basename "$$f")"; \
	done
	# Generate SSH host keys if not present
	@if [ ! -f generated/ssh-host-keys/ssh_host_rsa_key ]; then \
		echo "Generating SSH host keys"; \
		ssh-keygen -t rsa -b 4096 -f generated/ssh-host-keys/ssh_host_rsa_key -N "" -q; \
		ssh-keygen -t ecdsa -b 256 -f generated/ssh-host-keys/ssh_host_ecdsa_key -N "" -q; \
		ssh-keygen -t ed25519 -f generated/ssh-host-keys/ssh_host_ed25519_key -N "" -q; \
	fi
	# Generate SSH portal/token host key if not present
	@if [ ! -f generated/ssh-host-keys/ssh_portal_ed25519_key ]; then \
		echo "Generating SSH portal host keys"; \
		ssh-keygen -t ed25519 -f generated/ssh-host-keys/ssh_portal_ed25519_key -N "" -q; \
	fi

# --- Core system setup ---
k3s:
	@echo "Installing k3s"
	curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable=traefik --disable=servicelb --write-kubeconfig-mode 644" sh -
	sudo mkdir -p $$(dirname $(KUBECONFIG))
	sudo cp /etc/rancher/k3s/k3s.yaml $(KUBECONFIG)
	sudo chmod 644 $(KUBECONFIG)
	envsubst $(ENVSUBST_VARS) < config/k3s.yml.tpl > /tmp/registries.yaml
	sudo mv /tmp/registries.yaml /etc/rancher/k3s/registries.yaml
	sudo systemctl restart k3s

system:
	@echo "Configuring system"
	# Set inotify limits (required for k8s)
	# Persist via sysctl.d so they survive reboots (especially on immutable distros)
	sudo sysctl fs.inotify.max_user_instances=8192
	sudo sysctl fs.inotify.max_user_watches=524288
	@echo "fs.inotify.max_user_instances=8192" | sudo tee /etc/sysctl.d/99-lagoon.conf > /dev/null
	@echo "fs.inotify.max_user_watches=524288" | sudo tee -a /etc/sysctl.d/99-lagoon.conf > /dev/null
	# Install NFS support
	@if [ -f /run/ostree-booted ]; then \
		echo "Immutable OS detected (ostree/atomic)"; \
		if ! rpm -q nfs-utils >/dev/null 2>&1; then \
			echo "Installing nfs-utils via rpm-ostree (reboot required after install)"; \
			sudo rpm-ostree install -y --allow-inactive nfs-utils; \
			echo "NOTE: You may need to reboot for NFS support to take effect."; \
		else \
			echo "nfs-utils already available"; \
		fi; \
	elif command -v apt-get >/dev/null 2>&1; then \
		sudo apt-get update && sudo apt-get install -y nfs-common; \
	elif command -v dnf >/dev/null 2>&1; then \
		sudo dnf install -y nfs-utils; \
	elif command -v yum >/dev/null 2>&1; then \
		sudo yum install -y nfs-utils; \
	elif command -v pacman >/dev/null 2>&1; then \
		sudo pacman -S --noconfirm nfs-utils; \
	else \
		echo "Warning: Could not detect package manager. Install NFS client manually."; \
	fi

helm-repos: helm
	@echo "Adding helm repos"
	helm repo add harbor https://helm.goharbor.io
	helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
	helm repo add stable https://charts.helm.sh/stable
	# Note: PostgreSQL and MariaDB use cloudpirates OCI charts (no repo needed)
	helm repo add amazeeio https://amazeeio.github.io/charts/
	helm repo add lagoon https://uselagoon.github.io/lagoon-charts/
	helm repo add minio https://charts.min.io/
	helm repo add nats https://nats-io.github.io/k8s/helm/charts/
	helm repo add metallb https://metallb.github.io/metallb
	helm repo add jetstack https://charts.jetstack.io
	helm repo add jouve https://jouve.github.io/charts/
	helm repo add twuni https://twuni.github.io/docker-registry.helm
	helm repo add k8up https://k8up-io.github.io/k8up
	helm repo add appuio https://charts.appuio.ch
	helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
	helm repo add headlamp https://kubernetes-sigs.github.io/headlamp/
	helm repo add gatekeeper https://open-policy-agent.github.io/gatekeeper/charts
	helm repo update

metallb:
	@echo "Installing MetalLB"
	helm upgrade \
		--install \
		--create-namespace \
		--namespace metallb-system \
		--wait \
		metallb \
		metallb/metallb
	envsubst $(ENVSUBST_VARS) < config/metallb.yml.tpl > build/metallb.yml
	kubectl apply -f build/metallb.yml

cert-manager:
	@echo "Installing cert-manager"
	helm upgrade \
		--install \
		--create-namespace \
		--namespace cert-manager \
		--wait \
		-f build/values/cert-manager.yml \
		cert-manager \
		jetstack/cert-manager
	# Generate self-signed CA if using self-signed mode
	@if [ "$(TLS_MODE)" = "selfsigned" ]; then \
		mkdir -p certs; \
		if ! openssl x509 -enddate -noout -in certs/rootCA.pem > /dev/null 2>&1; then \
			echo "Generating self-signed root CA"; \
			openssl genrsa -out certs/rootCA-key.pem 2048; \
			openssl req -x509 -new -nodes -key certs/rootCA-key.pem \
				-sha256 -days 3560 -out certs/rootCA.pem \
				-addext keyUsage=critical,digitalSignature,keyEncipherment,keyCertSign \
				-subj '/CN=lagoon.test'; \
		fi; \
		kubectl -n cert-manager create secret generic lagoon-secret \
			--from-file=tls.crt=certs/rootCA.pem \
			--from-file=tls.key=certs/rootCA-key.pem \
			--from-file=ca.crt=certs/rootCA.pem \
			--dry-run=client -o yaml | kubectl apply -f -; \
	fi
	# Apply cluster issuers based on TLS mode
	kubectl apply -f build/config/lagoon-issuer-selfsigned.yml
	@if [ "$(TLS_MODE)" = "letsencrypt" ] || [ "$(TLS_MODE)" = "cloudflare" ]; then \
		kubectl apply -f build/config/lagoon-issuer-letsencrypt.yml; \
		kubectl apply -f build/config/lagoon-issuer-letsencrypt-staging.yml; \
	fi
	@if [ "$(TLS_MODE)" = "cloudflare" ]; then \
		kubectl apply -f build/config/lagoon-issuer-cloudflare.yml; \
	fi
	# Install trust-manager for CA distribution
	helm upgrade \
		--install \
		--create-namespace \
		--namespace cert-manager \
		--wait \
		--version=v0.19.0 \
		--set crds.enabled=true \
		--set secretTargets.enabled=true \
		--set secretTargets.authorizedSecretsAll=true \
		trust-manager \
		jetstack/trust-manager
	kubectl apply -f config/ca-bundle.yml

gatekeeper:
	@echo "Installing Gatekeeper"
	helm upgrade \
		--install \
		--create-namespace \
		--namespace gatekeeper-system \
		--wait \
		--version=v3.11.0 \
		--set replicas=1 \
		gatekeeper \
		gatekeeper/gatekeeper
	kubectl apply -f config/ca-volume.yml

ingress:
	@echo "Installing Ingress Nginx"
	helm upgrade \
		--install \
		--create-namespace \
		--namespace ingress-nginx \
		--wait \
		-f build/values/ingress-nginx.yml \
		ingress-nginx \
		ingress-nginx/ingress-nginx

harbor:
	@echo "Installing Harbor registry"
	helm upgrade \
		--install \
		--create-namespace \
		--namespace harbor \
		--wait \
		--version=1.16.2 \
		-f build/values/harbor.yml \
		harbor \
		harbor/harbor

registry:
	@echo "Installing unauthenticated registry"
	helm upgrade \
		--install \
		--create-namespace \
		--namespace registry \
		--wait \
		--set ingress.enabled=true \
		--set "ingress.hosts[0]=registry.$$($(KUBECTL) -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}').nip.io" \
		--set ingress.path="/" \
		--set persistence.enabled=true \
		--version=2.2.3 \
		registry \
		twuni/docker-registry

minio:
	@echo "Installing MinIO"
	helm upgrade \
		--install \
		--create-namespace \
		--namespace minio \
		--wait \
		-f build/values/minio.yml \
		minio \
		oci://registry-1.docker.io/cloudpirates/minio
	$(KUBECTL) -n minio exec -it $$($(KUBECTL) -n minio get pod -l app.kubernetes.io/name=minio -o jsonpath="{.items[0].metadata.name}") \
		-- sh -c 'mc alias set local http://localhost:9000 admin $(MINIO_PASSWORD) && mc mb local/lagoon-files && mc mb local/restores' || true

postgres:
	@echo "Installing PostgreSQL"
	helm upgrade \
		--install \
		--create-namespace \
		--namespace postgresql \
		--wait \
		--set auth.postgresPassword="$(POSTGRES_PASSWORD)" \
		postgresql \
		oci://registry-1.docker.io/cloudpirates/postgres

mariadb:
	@echo "Installing MariaDB"
	helm upgrade \
		--install \
		--create-namespace \
		--namespace mariadb \
		--wait \
		--set auth.rootPassword="$(MARIADB_PASSWORD)" \
		mariadb \
		oci://registry-1.docker.io/cloudpirates/mariadb

prometheus:
	@echo "Installing Prometheus Stack"
	helm upgrade \
		--install \
		--create-namespace \
		--namespace kube-prometheus \
		--wait \
		kube-prometheus \
		prometheus-community/kube-prometheus-stack \
		-f build/values/prometheus.yml

headlamp:
	@echo "Installing Headlamp"
	helm upgrade \
		--install \
		--create-namespace \
		--namespace headlamp \
		--wait \
		-f build/values/headlamp.yml \
		headlamp \
		headlamp/headlamp

# --- Lagoon components ---
lagoon-core:
	@echo "Installing Lagoon Core"
	kubectl create namespace lagoon-core --dry-run=client -o yaml | kubectl apply -f -
	kubectl -n lagoon-core apply -f build/config/nats-cert.yml
	kubectl -n lagoon-core apply -f build/config/broker-tls.yml
	helm upgrade \
		--install \
		--create-namespace \
		--namespace lagoon-core \
		--wait \
		--timeout 10m \
		-f build/values/lagoon-core.yml \
		--set buildDeployImage.default.image="registry.$$($(KUBECTL) -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}').nip.io/library/build-deploy-image:edge" \
		--set elasticsearchURL="not-real-but-necessary.example.com" \
		--set kibanaURL="not-real-but-necessary.example.com" \
		--set keycloak.serviceMonitor.enabled=false \
		--set broker.serviceMonitor.enabled=false \
		--set drushAlias.enabled=false \
		--set backupHandler.enabled=false \
		--set sshToken.enabled=false \
		--set sshToken.serviceMonitor.enabled=false \
		--set-file ssh.hostKeys.rsa=generated/ssh-host-keys/ssh_host_rsa_key \
		--set-file ssh.hostKeys.rsaPub=generated/ssh-host-keys/ssh_host_rsa_key.pub \
		--set-file ssh.hostKeys.ecdsa=generated/ssh-host-keys/ssh_host_ecdsa_key \
		--set-file ssh.hostKeys.ecdsaPub=generated/ssh-host-keys/ssh_host_ecdsa_key.pub \
		--set-file ssh.hostKeys.ed25519=generated/ssh-host-keys/ssh_host_ed25519_key \
		--set-file ssh.hostKeys.ed25519Pub=generated/ssh-host-keys/ssh_host_ed25519_key.pub \
		--set-file sshToken.hostKeys.ed25519=generated/ssh-host-keys/ssh_portal_ed25519_key \
		lagoon-core \
		lagoon/lagoon-core

lagoon-remote:
	@echo "Installing Lagoon Remote"
	kubectl create namespace lagoon --dry-run=client -o yaml | kubectl apply -f -
	kubectl -n lagoon apply -f build/config/remote-nats-cert.yml
	kubectl -n lagoon apply -f build/config/remote-cert.yml
	kubectl apply -f config/bulk-storage.yml
	helm upgrade \
		--install \
		--create-namespace \
		--namespace lagoon \
		--wait \
		-f build/values/lagoon-remote.yml \
		--set "dockerHost.registry=registry.$$($(KUBECTL) -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}').nip.io" \
		--set "global.rabbitMQPassword=$$($(KUBECTL) -n lagoon-core get secret lagoon-core-broker -o json | jq -r '.data.RABBITMQ_PASSWORD | @base64d')" \
		--set "lagoon-build-deploy.rabbitMQPassword=$$($(KUBECTL) -n lagoon-core get secret lagoon-core-broker -o json | jq -r '.data.RABBITMQ_PASSWORD | @base64d')" \
		--set "lagoon-build-deploy.unauthenticatedRegistry=registry.$$($(KUBECTL) -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}').nip.io" \
		--set-file sshPortal.hostKeys.ed25519=generated/ssh-host-keys/ssh_portal_ed25519_key \
		lagoon-remote \
		lagoon/lagoon-remote

# --- Tools ---
lagoon-config: jwt jq lagoon-cli post-install

helm:
	@if ! command -v helm >/dev/null; then \
		echo "Installing Helm"; \
		curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash; \
	else echo "Helm already installed"; fi

jwt:
	@if ! command -v jwt >/dev/null; then \
		echo "Installing jwt-cli"; \
		TMPDIR=$$(mktemp -d); \
		if [ "$(OS)" = "darwin" ]; then \
			curl -sSL https://github.com/mike-engel/jwt-cli/releases/download/6.2.0/jwt-macOS.tar.gz | tar -xzC $$TMPDIR; \
		elif [ "$(ARCH)" = "arm64" ]; then \
			curl -sSL https://github.com/mike-engel/jwt-cli/releases/download/6.2.0/jwt-linux.tar.gz | tar -xzC $$TMPDIR; \
		else \
			curl -sSL https://github.com/mike-engel/jwt-cli/releases/download/6.2.0/jwt-linux-musl.tar.gz | tar -xzC $$TMPDIR; \
		fi; \
		sudo mv $$TMPDIR/jwt /usr/local/bin/jwt; \
		rm -rf $$TMPDIR; \
		chmod a+x /usr/local/bin/jwt; \
	else echo "jwt-cli already installed"; fi

jq:
	@if ! command -v jq >/dev/null; then \
		echo "Installing jq"; \
		if command -v apt-get >/dev/null 2>&1; then \
			sudo apt-get update && sudo apt-get install -y jq; \
		elif command -v dnf >/dev/null 2>&1; then \
			sudo dnf install -y jq; \
		elif command -v yum >/dev/null 2>&1; then \
			sudo yum install -y jq; \
		elif command -v pacman >/dev/null 2>&1; then \
			sudo pacman -S --noconfirm jq; \
		elif command -v brew >/dev/null 2>&1; then \
			brew install jq; \
		else \
			echo "Error: Could not detect package manager. Install jq manually."; \
			exit 1; \
		fi; \
	else echo "jq already installed"; fi

lagoon-cli:
	@if ! command -v lagoon >/dev/null; then \
		echo "Installing Lagoon CLI"; \
		sudo curl -L "https://github.com/uselagoon/lagoon-cli/releases/download/v0.32.1/lagoon-cli-v0.32.1-$(OS)-$(ARCH)" \
			-o /usr/local/bin/lagoon; \
		sudo chmod +x /usr/local/bin/lagoon; \
	else echo "Lagoon CLI already installed"; fi

# --- Lagoon post-install configuration ---
post-install:
	@echo "Configuring Lagoon"
	# Wait for API to be reachable (Keycloak migrations can take several minutes)
	@echo "Waiting for Lagoon API to become ready..."
	@ATTEMPTS=0; MAX_ATTEMPTS=60; \
	while [ $$ATTEMPTS -lt $$MAX_ATTEMPTS ]; do \
		STATUS=$$(curl -s -k -o /dev/null -w '%{http_code}' http://api.$(DOMAIN)/graphql 2>/dev/null || echo "000"); \
		if [ "$$STATUS" = "200" ] || [ "$$STATUS" = "405" ]; then \
			echo "API is ready (HTTP $$STATUS)"; \
			break; \
		fi; \
		ATTEMPTS=$$((ATTEMPTS + 1)); \
		echo "  Attempt $$ATTEMPTS/$$MAX_ATTEMPTS — API returned HTTP $$STATUS, retrying in 10s..."; \
		sleep 10; \
	done; \
	if [ $$ATTEMPTS -ge $$MAX_ATTEMPTS ]; then \
		echo "ERROR: API did not become ready after $$MAX_ATTEMPTS attempts"; \
		echo "Check pod status: kubectl -n lagoon-core get pods"; \
		exit 1; \
	fi
	# Wait for Keycloak to be reachable
	@echo "Waiting for Keycloak to become ready..."
	@ATTEMPTS=0; MAX_ATTEMPTS=60; \
	while [ $$ATTEMPTS -lt $$MAX_ATTEMPTS ]; do \
		STATUS=$$(curl -s -k -o /dev/null -w '%{http_code}' https://keycloak.$(DOMAIN)/auth/ 2>/dev/null || echo "000"); \
		if [ "$$STATUS" = "200" ] || [ "$$STATUS" = "303" ]; then \
			echo "Keycloak is ready (HTTP $$STATUS)"; \
			break; \
		fi; \
		ATTEMPTS=$$((ATTEMPTS + 1)); \
		echo "  Attempt $$ATTEMPTS/$$MAX_ATTEMPTS — Keycloak returned HTTP $$STATUS, retrying in 10s..."; \
		sleep 10; \
	done; \
	if [ $$ATTEMPTS -ge $$MAX_ATTEMPTS ]; then \
		echo "ERROR: Keycloak did not become ready after $$MAX_ATTEMPTS attempts"; \
		echo "Check pod status: kubectl -n lagoon-core get pods"; \
		exit 1; \
	fi
	# Obtain JWT token
	@JWTUSER=localadmin; \
	JWTAUDIENCE=api.dev; \
	JWTSECRET=$$(kubectl get secret -n lagoon-core lagoon-core-secrets -o json | jq -r '.data.JWTSECRET | @base64d'); \
	TOKEN=$$(jwt encode --alg HS256 --no-iat --payload role=admin --iss "$$JWTUSER" --aud "$$JWTAUDIENCE" --sub "$$JWTUSER" --secret "$$JWTSECRET"); \
	echo "Creating user $(ADMIN_EMAIL)"; \
	QUERY='mutation ($$email: String!, $$firstName: String, $$lastName: String, $$comment: String) { addUser(input: { email: $$email, firstName: $$firstName, lastName: $$lastName, comment: $$comment }) { id email firstName lastName } }'; \
	VARIABLES='{"email": "$(ADMIN_EMAIL)", "firstName": "$(ADMIN_FIRST_NAME)", "lastName": "$(ADMIN_LAST_NAME)", "comment": "Created via installer"}'; \
	RESULT=$$(curl -s -k -X POST http://api.$(DOMAIN)/graphql \
		-H "Content-Type: application/json" \
		-H "Authorization: Bearer $$TOKEN" \
		-d "$$(jq -n --arg query "$$QUERY" --argjson variables "$$VARIABLES" '{query: $$query, variables: $$variables}')"); \
	echo "$$RESULT"; \
	echo "Assigning platform owner role"; \
	QUERY='mutation ($$user: UserInput!, $$role: PlatformRole!) { addPlatformRoleToUser(user: $$user, role: $$role) { id email platformRoles } }'; \
	VARIABLES='{ "user": { "email": "$(ADMIN_EMAIL)" }, "role": "OWNER" }'; \
	RESULT=$$(curl -s -k -X POST http://api.$(DOMAIN)/graphql \
		-H "Content-Type: application/json" \
		-H "Authorization: Bearer $$TOKEN" \
		-d "$$(jq -n --arg query "$$QUERY" --argjson variables "$$VARIABLES" '{query: $$query, variables: $$variables}')"); \
	echo "$$RESULT"; \
	echo "Adding SSH key"; \
	SSH_KEY_NAME="lagoon-admin"; \
	SSH_KEY_VALUE=$$(cat $(SSH_KEY_PATH).pub); \
	JSON=$$(printf '{"query":"mutation { addUserSSHPublicKey(input: {name: \\"%s\\", publicKey: \\"%s\\", user: {email: \\"%s\\"}}) { id } }"}' "$$SSH_KEY_NAME" "$$SSH_KEY_VALUE" "$(ADMIN_EMAIL)"); \
	RESULT=$$(curl -s -k -X POST http://api.$(DOMAIN)/graphql \
		-H 'Content-Type: application/json' \
		-H "Authorization: Bearer $$TOKEN" \
		-d "$$JSON"); \
	echo "$$RESULT"; \
	echo "Getting Keycloak token"; \
	KEYCLOAK_URL=https://keycloak.$(DOMAIN); \
	KEYCLOAK_SECRET=$$(kubectl -n lagoon-core get secret lagoon-core-keycloak -o jsonpath='{.data.KEYCLOAK_ADMIN_API_CLIENT_SECRET}' | base64 --decode); \
	KEYCLOAK_RESPONSE=$$(curl -s -k -X POST "$${KEYCLOAK_URL}/auth/realms/master/protocol/openid-connect/token" \
		-d "grant_type=client_credentials" \
		-d "client_id=admin-api" \
		-d "client_secret=$$KEYCLOAK_SECRET"); \
	KEYCLOAK_TOKEN=$$(echo "$$KEYCLOAK_RESPONSE" | jq -r '.access_token'); \
	if [ -z "$$KEYCLOAK_TOKEN" ] || [ "$$KEYCLOAK_TOKEN" = "null" ]; then \
		echo "ERROR: Failed to obtain Keycloak token"; \
		echo "Response: $$KEYCLOAK_RESPONSE"; \
		exit 1; \
	fi; \
	echo "Resetting password for $(ADMIN_EMAIL)"; \
	USER_JSON=$$(curl -s -k -H "Authorization: Bearer $$KEYCLOAK_TOKEN" \
		-H "Content-Type: application/json" \
		"$${KEYCLOAK_URL}/auth/admin/realms/lagoon/users?email=$(ADMIN_EMAIL)"); \
	USER_ID=$$(echo $$USER_JSON | jq -r '.[0].id'); \
	if [ -z "$$USER_ID" ] || [ "$$USER_ID" = "null" ]; then \
		echo "Warning: User not found in Keycloak, skipping password reset"; \
	else \
		curl -s -k -X PUT \
			-H "Authorization: Bearer $$KEYCLOAK_TOKEN" \
			-H "Content-Type: application/json" \
			-d '{"type": "password", "value": "'"$(ADMIN_PASSWORD)"'", "temporary": false}' \
			"$${KEYCLOAK_URL}/auth/admin/realms/lagoon/users/$$USER_ID/reset-password"; \
	fi; \
	echo "Configuring Lagoon CLI"; \
	SSH_HOST=$$(kubectl get svc -n lagoon-core lagoon-core-ssh -o jsonpath='{.status.loadBalancer.ingress[0].ip}'); \
	lagoon config add \
		--force \
		--graphql http://api.$(DOMAIN)/graphql \
		--ui http://dashboard.$(DOMAIN) \
		--hostname $$SSH_HOST \
		--lagoon $(ORG_NAME) \
		--port 2020 \
		--ssh-key "$(SSH_KEY_PATH)"; \
	lagoon config default --lagoon $(ORG_NAME); \
	lagoon login; \
	echo "Configuring organization and deploy targets"; \
	if lagoon list organizations --output-json | jq -e '.data[] | select(.name=="$(ORG_NAME)")' >/dev/null 2>&1; then \
		echo "Organization $(ORG_NAME) already exists"; \
	else \
		lagoon add organization --force -O $(ORG_NAME); \
	fi; \
	CONSOLE_URL=$$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'); \
	if lagoon list deploytargets --output-json | jq -e '.data // [] | .[] | select(.name=="$(ORG_NAME)")' >/dev/null 2>&1; then \
		echo "Deploytarget $(ORG_NAME) already exists"; \
	else \
		lagoon add deploytarget \
			--name $(ORG_NAME) \
			--force \
			--token "$$TOKEN" \
			--console-url "$$CONSOLE_URL" \
			--router-pattern='$${environment}-$${project}.app.$(DOMAIN)'; \
	fi; \
	DEPLOYTARGET_ID=$$(lagoon list deploytargets --output-json | jq -r '.data[] | select(.name=="$(ORG_NAME)") | .id'); \
	if lagoon list organization-deploytargets -O $(ORG_NAME) --output-json | jq -e --arg id "$$DEPLOYTARGET_ID" '.data[] | select(.id==$$id)' >/dev/null 2>&1; then \
		echo "Deploytarget already linked to organization"; \
	else \
		lagoon add organization-deploytarget -O $(ORG_NAME) -D "$$DEPLOYTARGET_ID"; \
	fi

build-deploy-tool:
	export BDT_DIR=$$(mktemp -d ./build/bdt.XXX) \
		&& ln -sfn "$$BDT_DIR" ./build/bdt \
		&& git clone git@github.com:LagoonAtHome/build-deploy-tool.git "$$BDT_DIR" \
		&& cd "$$BDT_DIR" \
		&& git checkout nfs-volumes \
		&& make docker-build

push-local-build-image:
	@export KUBECONFIG="$$KUBECONFIG" && \
		export IMAGE_REGISTRY="registry.$$($(KUBECTL) -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}').nip.io/library" \
		&& docker login -u admin -p Harbor12345 $$IMAGE_REGISTRY \
		&& docker tag lagoon/build-deploy-image:local $$IMAGE_REGISTRY/build-deploy-image:edge \
		&& docker push $$IMAGE_REGISTRY/build-deploy-image:edge

# --- Cleanup ---
clean-bdt:
	@for dir in ./build/bdt.* ; do \
		if [ -d $$dir ]; then \
			echo "removing directory $$dir" ; \
			rm -rf $$dir ; \
		fi ; \
	done
	rm -f ./build/bdt

clean-ssh:
	ssh-keygen -R [$$($(KUBECTL) get svc -n lagoon-core lagoon-core-ssh -o jsonpath='{.status.loadBalancer.ingress[0].ip}')]:2020

nuke: clean-bdt clean-ssh
	@echo "Nuking EVERYTHING"
	bash /usr/local/bin/k3s-uninstall.sh
	sudo rm -rf $(KUBECONFIG)
